### ISSUE TITLE
Update config format.

### ISSUE THREAD

**Issue by zef** [philipsun-cu/ATLAS-iOS-Fall-22#2]
Hey Jaiji! The [format I'm looking for](https://zef.github.io/ATLAS-iOS/repo_requirements.html) in this file would be as follows:

```yaml
name: Jiaji Sun

repo_names:
  - On-Campus-Navigation-System-for-Disabled-Student

10-ux-ui-criticism:
  - https://vimeo.com/756194873

11-models-from-data:
  - https://github.com/philipsun-cu/On-Campus-Navigation-System-for-Disabled-Student/blob/main/navi/navi/navi/ContentView.swift#L17
```

Could you please update the file with that format when you have a chance?

Thank you!

https://github.com/philipsun-cu/ATLAS-iOS-Fall-22/blob/478224f2d375263922892888518b00d6a694422e/config.yml#L1-L8
